package com.orchedule.scheduling.domain;

import com.orchedule.scheduling.application.exception.InvalidScheduleException;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Aggregate root representing one round (jornada) of a season's schedule:
 * a week number plus the list of team-to-slot assignments generated by the
 * RotationEngine for that week.
 */
public class ScheduleRound {

    private final UUID id;
    private final UUID seasonId;
    private final int weekNumber;
    private ScheduleRoundStatus status;
    private final List<TeamAssignment> assignments;
    private final OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

    public ScheduleRound(UUID id, UUID seasonId, int weekNumber, ScheduleRoundStatus status,
                          List<TeamAssignment> assignments, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        this.id = id;
        this.seasonId = seasonId;
        this.weekNumber = weekNumber;
        this.status = status;
        this.assignments = new ArrayList<>(assignments);
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public static ScheduleRound createDraft(UUID seasonId, int weekNumber, List<TeamAssignment> assignments) {
        if (assignments == null || assignments.isEmpty()) {
            throw new InvalidScheduleException("A schedule round must contain at least one assignment");
        }
        OffsetDateTime now = OffsetDateTime.now();
        return new ScheduleRound(UUID.randomUUID(), seasonId, weekNumber, ScheduleRoundStatus.DRAFT,
                assignments, now, now);
    }

    public void confirm() {
        if (status == ScheduleRoundStatus.CANCELLED) {
            throw new IllegalStateException("Cannot confirm a cancelled round");
        }
        this.status = ScheduleRoundStatus.CONFIRMED;
        touch();
    }

    public void cancel() {
        this.status = ScheduleRoundStatus.CANCELLED;
        touch();
    }

    public void replaceAssignments(List<TeamAssignment> newAssignments) {
        if (status == ScheduleRoundStatus.CONFIRMED) {
            throw new IllegalStateException("Cannot modify assignments of a confirmed round");
        }
        if (newAssignments == null || newAssignments.isEmpty()) {
            throw new InvalidScheduleException("A schedule round must contain at least one assignment");
        }
        this.assignments.clear();
        this.assignments.addAll(newAssignments);
        touch();
    }

    private void touch() {
        this.updatedAt = OffsetDateTime.now();
    }

    public UUID getId() { return id; }
    public UUID getSeasonId() { return seasonId; }
    public int getWeekNumber() { return weekNumber; }
    public ScheduleRoundStatus getStatus() { return status; }
    public List<TeamAssignment> getAssignments() { return List.copyOf(assignments); }
    public OffsetDateTime getCreatedAt() { return createdAt; }
    public OffsetDateTime getUpdatedAt() { return updatedAt; }
}
